language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
scripts:
  - npm install codecov -g
  - npm test
  - codecov -f coverage/*.json
node_js:
  - '10'
  - '8'
  - '6'
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
