language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
scripts:
  - npm install codecov -g
after_success:
  - codecov
node_js:
  - '10'
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
